# -*- coding: utf-8 -*-
"""4/10/2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QdVqHeCz3WwCDLG_rYn0mIV2SLz7OnyR
"""



import pandas as pd
data={'productname'   :['mobile','tshirts','detergent','tv','pant'],
      'category'      :['electronics','clothing','home & kitchen','elkectronics','clothing'],
      'price'         :[5000,150,50,10000,300],
      'quatntity sold':[2,3,5,2,3],
}
df=pd.DataFrame(data)
pd.pivot_table(df,index='category',values='price',aggfunc='mean')

import pandas as pd
data={'productname'   :['mobile','tshirts','detergent','tv','pant'],
      'category'      :['electronics','clothing','home & kitchen','elkectronics','clothing'],
      'price'        :[5000,150,50,10000,300],
      'quantity_sold':[2,3,5,2,3],
}
df=pd.DataFrame(data)
df['total_revenue']=df['price']*df['quantity_sold']
pd.pivot_table(df,index='category',values=['total_revenue','price'],aggfunc={'total_revenue':'sum','price':'mean'})

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('/content/mtcars.csv')
df.head()

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('/content/mtcars.csv')
plt.hist(df['mpg'])
plt.xlabel('miles per gallon')
plt.ylabel('frequency')
plt.title('histogram')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('/content/mtcars.csv')
plt.scatter(df['wt'],df['mpg'])
plt.xlabel(' miles per gallon')
plt.title('scatter plot ')
plt.ylabel(' wight of the car')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('/content/mtcars.csv')
trans=df['am'].value_counts()
trans.plot(kind='bar')
plt.title(' bar plot ')
plt.ylabel('frequency')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('/content/mtcars.csv')
plt.boxplot(df['mpg'])
plt.title('box plot ')
plt.xlabel()
plt.show()